# workload Job
apiVersion: batch/v1
kind: Job
metadata:
  name: ex-job
  namespace: nginx-deployment
  labels:
    app: ex-job
spec:
  completions: 3
  parallelism: 2
  template:
    metadata:
      labels:
        app: ex-job
    spec:
      containers:
        - name: ex-job
          image: centos
          command: ["/bin/bash", "-c", "echo hello world"]
      restartPolicy: Never
