# workload ReplicaSet
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-deployment
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
  namespace: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "256m"
            requests:
              memory: "64Mi"
              cpu: "128m"
