# workload statefulSet
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: nginx-deployment
  labels:
    app: mariadb
spec:
  ports:
    - port: 3006
      name: mariadb
  clusterIP: None
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-deployment
  namespace: nginx-deployment
  labels:
    app: mariadb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3006
          env:
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "0" # if it is 1 and root_password is set, root_password takes precedance
            - name: MARIADB_ROOT_PASSWORD
              value: secret
