# // create configmap with json file

apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ex
  namespace: nginx-deployment
data:
  db_host: "localhost"
  db_port: "5432"

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
  namespace: nginx-deployment
spec:
  containers:
  - name: nginx
    image: minhquang31122000/configmap-and-secret
    env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: configmap-ex
          key: db_host
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: configmap-ex
          key: db_port
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never