# // create secret with json file

apiVersion: v1
kind: Secret
metadata:
  name: secret-ex
  namespace: nginx-deployment
type: Opaque
data:
  username: QWRtaW4=
  password: UXVhbmd0ZW8x

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  namespace: nginx-deployment
spec:
  containers:
  - name: secret-ex-container
    image: minhquang31122000/configmap-and-secret
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-ex
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-ex
          key: password
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never