apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon-set
  namespace: nginx-deployment
  labels:
    app: nginx-daemon-set
spec:
  selector:
    matchLabels:
      app: nginx-daemon-set
  template:
    metadata:
      labels:
        app: nginx-daemon-set
    spec:
      containers:
        - name: nginx-daemon-set
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "256m"
            requests:
              memory: "64Mi"
              cpu: "128m"
